version: '3.7'

services:
  # Backend Service
  app:
    build:
      context: backend/
      dockerfile: Dockerfile
    ports:
      - "8077:8077" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: always
    depends_on:
      - db # This service depends on mysql. Start that first.
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://db/boxinatordb?serverTimezone=UTC&autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: boxinator
      SPRING_DATASOURCE_PASSWORD: 123456
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
      - frontend

    # Frontend Service
  app-client:
    build:
      context: frontend/
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - app
    networks:
      - frontend

  # Database Service (Mysql)
  db:
    image: mysql:5.7
    ports:
      - "8076:3306"
    restart: always
    environment:
      MYSQL_DATABASE: boxinatordb
      MYSQL_USER: boxinator
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend

volumes:
  db-data:

networks:
  backend:
  frontend: 